name: Daily Meme

on:
  schedule:
    - cron: '50 7 * * *'
  workflow_dispatch:

jobs:
  send-meme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Send Meme
        env:
          WEBHOOK_URLS: ${{ secrets.WEBHOOK_URLS }}
          WALLHAVEN_API_KEY: ${{ secrets.WALLHAVEN_API_KEY }}
        run: node meme-sender.js
